export const ActionTypes = {
  //defining action types
  SET_RATES: "SET_RATES",
  SET_SYMBOLES: "SET_SYMBOLES",
  SET_CURRENCY_PER_COUNTRY: "SET_CURRENCY_PER_COUNTRY",
  SET_SELECTED_CODE: "SET_SELECTED_CODE",
  SET_SELECTED_CURRENCY: "SET_SELECTED_CURRENCY",
};
